bots:
  ChitchatBot:
    prefix: '&8[&2BOT&8]&4ChitchatBot&7: &f'
    listensTo: []
    requires_perm: false
    talks: true
    freqTicks: 7000
    challengeChance: 0.3
    word_limit: 10000
  HQMBot:
    prefix: '&8[&2BOT&8]&3HQMBot&7: &f'
    listensTo:
      - 'HQM'
      - 'HmmmQuestionMark'
      - 'HmmmQM'
    requires_perm: false
    talks: false
    freqTicks: 0
    challengeChance: 0.0
    word_limit: 10000