bots:
  GustaBot:
    prefix: '&8[&dF&8]&6[&2BOT&6]&4GustaBot&7: &f'
    listensTo: []
    talks: true
    freqTicks: 7000
    challengeChance: 0.3
    word_limit: 10000
  HQMBot:
    prefix: '&8[&dF&8]&6[&2BOT&6]&3HQMBot&7: &f'
    listensTo:
      - 'HQM'
      - 'HmmmQuestionMark'
      - 'HandyQuestMarker'
    talks: false
    freqTicks: 0
    challengeChance: 0.0
    word_limit: 10000
  PandaBot:
    prefix: '&8[&dF&8]&6[&2BOT&6]&f&lPandaBot&7: &f'
    listensTo:
      - 'ChosenPanda'
    talks: false
    freqTicks: 0
    challengeChance: 0.0
    word_limit: 10000
  MausBot:
    prefix: '&8[&dF&8]&6[&2BOT&6]&2MausBot&7: &f'
    listensTo:
      - 'janie177'
    talks: false
    freqTicks: 0
    challengeChance: 0.0
    word_limit: 10000