name: ${project.name}
main: com.demigodsrpg.chitchatbot.BotPlugin
version: ${project.version}
description: ${project.description}
authors: [HmmmQuestionMark]
depend: [Chitchat]
commands:
  chitchatbot:
    usage: /chitchatbot <info|purge> <bot>
    alias: [ccb]
permissions:
  chitchatbot.info:
    default: op
